POST http://localhost:3000/reports
content-type: application/json

{
    "make": "chevrolet",
    "model": "onix",
    "year": 2016,
    "mileage": 60000,
    "lng": 0,
    "lat": 0,
    "price": 48000
}

### Update request
PATCH http://localhost:3000/reports/2
content-type: application/json

{
    "approved": false
}