POST http://localhost:3000/reports
content-type: application/json

{
    "approved": true,
    "make": "honda",
    "model": "city",
    "year": 2013,
    "mileage": 55000,
    "lng": 0,
    "lat": 0,
    "price": 15000
}