POST http://localhost:3000/reports
content-type: application/json

{
    "make": "chevrolet",
    "model": "onix",
    "year": 2016,
    "mileage": 60000,
    "lng": 0,
    "lat": 0,
    "price": 48000
}

### Update request
PATCH http://localhost:3000/reports/5
content-type: application/json

{
    "approved": false
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports/?make=toyota&model=corolla&lng=0&lat=0&mileage=100000&year=2018